// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MessageBoard.Models;

#nullable disable

namespace MessageBoard.Migrations
{
		[DbContext(typeof(MessageBoardContext))]
		[Migration("20240827212205_Initial")]
		partial class Initial
		{
				protected override void BuildTargetModel(ModelBuilder modelBuilder)
				{
#pragma warning disable 612, 618
						modelBuilder
								.HasAnnotation("ProductVersion", "6.0.0")
								.HasAnnotation("Relational:MaxIdentifierLength", 64);

						modelBuilder.Entity("MessageBoard.Models.Message", b =>
								{
										b.Property<int>("MessageId")
												.ValueGeneratedOnAdd()
												.HasColumnType("int");

										b.Property<string>("Content")
												.IsRequired()
												.HasMaxLength(400)
												.HasColumnType("varchar(400)");

										b.Property<string>("PostedOn")
												.IsRequired()
												.HasColumnType("longtext");

										b.Property<string>("Username")
												.IsRequired()
												.HasMaxLength(20)
												.HasColumnType("varchar(20)");

										b.HasKey("MessageId");

										b.ToTable("Message");
								});
#pragma warning restore 612, 618
				}
		}
}
